version: '3.9'

volumes:
  mysql_volume:
  cache_volume:

networks:
  forum_network:
    driver: bridge

services:
  api:
    image: heniojunior/forum-api:latest
#    restart: on-failure
    build: .
    working_dir: /app
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - forum_network
    depends_on:
      - mysqldb
      - cache
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3308/db-forum
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: cache
      SPRING_REDIS_PORT: 6379
    volumes:
      - .m2:/root/.m2
    
  mysqldb:
    image: mysql:8.0.30
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
    - "3308:3308"
    expose:
    - 3308
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - forum_network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: db-forum
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
  
  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - forum_network
    environment:
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache_volume:/data
