name: CI with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Mysql
        run: docker run --network host -e MYSQL_ROOT_PASSWORD=P@ssw0rd -e MYSQL_DATABASE=db_forum -e MYSQL_ROOT_HOST='%' -d mysql:8.0.30

      - name: Build Redis
        run: docker run -d -p 6379:6379 --network host --name redis redis:latest

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven

      - name: Build Application Jar
        working-directory: ./forum
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./forum
        run: docker-compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag heniojunior/forum-api:latest heniojunior/forum-api:${{github.run_id}}   
          docker push heniojunior/forum-api:${{github.run_id}}
          docker push heniojunior/forum-api:latest

